console.log('오늘은 "수요일"입니다.');
console.log("오늘은 '수요일'입니다.");
console.log('');
console.log("오늘은 '수요일'입니다.");
console.log(`오늘은 '수요일'입니다.`);
console.log(`오늘은 "수요일"입니다.`);
console.log('');
console.log(`아리스토텔레스는 "인간은 사회적 동물이다."라고 말했다.`);
console.log(`한국 영화 역사상 아카데미상을 받은 것은 '기생충'이 처음이다.`);
console.log(`영화 '기생충'에서 "제시카 외동딸 일리노이 기카고 과선배는`);
console.log(`김진모 그는 외사촌"라는 대사가 노래에 찰떡이었다.`);
console.log('');
console.log(2 + '2');
console.log(2 - '2');
